import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import Toaster from "./components/TosterProvider";
import TranstackProvider from "./components/Providers/tanstackProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  // const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body className={inter.className}>
        <TranstackProvider>
          <SessionProvider session={session}>
            <Toaster />
            {children}
          </SessionProvider>
        </TranstackProvider>
      </body>
      {/* </QueryClientProvider> */}
    </html>
  );
}
